site_name: Python Facebook Docs
site_description: Docs for python-facebook library
site_url: https://sns-sdks.github.io/python-facebook/
repo_url: https://github.com/sns-sdks/python-facebook
copyright: Copyright &copy; 2019 - 2021 Ikaros kun

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Usage:
      - Graph API: usage/graph-api.md
      - Server-Sent Events: usage/server-send-events.md
      - Threads Graph API: usage/threads-graph-api.md
  - Changelog: CHANGELOG.md
  - Previous Version Docs:
      - README: previous-version/readme.md
      - usage-en: previous-version/usage_en.md
      - 基础教程: previous-version/usage_zh.md
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/realllkk520
    - icon: fontawesome/brands/github
      link: https://github.com/sns-sdks/python-facebook

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji
